project:
  type: website

publish:
  gh-pages:
    branch: gh-pages    # Quarto will publish to this branch
    repo: annywm/ClimateSolution
  
website:
  title: Climate Solution
  navbar:
    left:
      - text: "Model"
        menu:
          - href: Introduction.qmd
            text: "Introduction"
          - href: parameters.qmd
            text: "Parameters"
          - href: equations.qmd
            text: "Equations"
          - href: variables.qmd
            text: "Variables"
            
      - href: timeline.qmd
        text: "Timeline"
      - href: reference.qmd
        text: "Reference"
      
      - text: "Datasets"
        menu:
          - href: soil.qmd
            text: "Soil Dataset"
          - href: climate.qmd
            text: "Climate Dataset"


    right:
      - icon: github
        href: https://github.com/ubc-litefarm-datateam/GHG-LiteFarm-MDS-Capstone
        text: Github

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
