---
title: "Parameter"
---

## GHG Emission Model Parameters

### Climate 

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| P | Annual growing season precipitation (May – October) | mm | $EF_{{CT}_{P}}$ | Common | Default(based on ecodistrict level) & External Source (NASA)| 
| PE | Annual growing season potential evapotranspiration (May – October)  | mm  | $EF_{{CT}_{PE}}$| Common | Default(based on ecodistrict level) & External Source(NASA) | 

### Soil

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| $FR_{Topo}$     | Fraction of land occupied by lower portions of landscape based on ecodistrict | unit | Emission Factor $EF_{Topo}$ (only for non-irrigated sites and dry environments) | Yes | Default(based on ecodistrict level)| 
| $RF_{TX}$    | a correction of the $EF_{Topo}$ in specific ecodistrict based on the soil texture  | unit  | $EF_{base}$| Yes| Default(based on ecodistrict level and soil type) | 
### Crop

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| Moisture | Moisture content of product | % | $C_p$ | Common | default Canada value (based on P and PE)| 
| $N_p$  | Nitrogen concentration in the product | kg N/kg | $Grain_N$ | Common | default (based on P and PE)| 
| $N_s$  | Nitrogen concentration in the straw | kg N/kg | $Straw_N$ | Common | default (based on P and PE)| 
| $N_r$      | Nitrogen concentration in the root | kg N/kg | $Root_N$ | Common | default (based on P and PE)| 
| $N_e$      | Nitrogen concentration in the extraroot | kg N/kg | $Exudate_N$ | Common | default (based on P and PE)| 
| $R_p$ | Relative biomass allocation coefficient for product | Unit |$C_s$, $C_r$,$C_e$ | Common | default (based on P and PE)| 
| $R_r$ | Relative biomass allocation coefficient for roots | Unit |$C_r$| Common | default (based on P and PE)| 
| $R_s$ | Relative biomass allocation coefficient for straw | Unit |$C_s$| Common | default (based on P and PE)| Any additional notes1 | Any additional notes2 |
| $R_e$ | Relative biomass allocation coefficient for extra-root | Unit |$C_e$| Common | default (based on P and PE)| 
| $C_{concentration}$ | Carbon concentration of all plant parts| kg C/kg |$C_p$| Common | default (based crop group)| 
| $S_p$ | Percentage of product yield returned to soil| % |$C_p$,$C_{p\_to\_soil}$| Common | default (based crop group)| 
| $S_s$ | Percentage of straw yield returned to soil| % |$Straw_N$,$C_s$| Common | default (based crop group)| 
| $S_r$ | Percentage of root yield returned to soil| % |$Root_N$,$C_r$| Common | default (based crop group)| 


### Modifiers(fertilizer)


| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| $RF_{CS}$ | Reduction factor for Cropping System| unit |$EF$| Common | default (based on perennial or annual)| 
| $RF_{NS}$    | Reduction factor for N sourse (SN = Synthetic Nitrogen; ON = Organic Nitrogen; CRN = Crop Residue Nitrogen )  | unit  | $EF$| NA| based on the | 
| $RF_{AM}$    | Reduction factor based on application method| unit  | $EF$| NA| based on the | 
| $RF_{Till}$    | Tillage modifier based on conservation or conventional Tillage| unit  | $EF$| NA| based on the | 




### Parameters for Crop Residue Nitrogen Calculation 

|Parameter groups|Parameters|Explanation|Data source|Related Function|
|---|---|---|---|---|---|
| Farm | Area | Numerical, total area of the farm (ha)| LiteFarm |
| Farm | Yield | Numerical, the estimated yield ($kg/ha$) | LiteFarm |
| Crop | Moisture | Moisture content of product (%) | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $N_p$ | N concentration in the product ($kg \ kg^{-1}$) | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $N_s$ | N concentration in the straw ($kg \ kg^{-1}$) | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $N_r$ | N concentration in the roots ($kg \ kg^{-1}$) | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $N_e$ | N concentration in the extra root material ($kg \ kg^{-1}$) | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $R_s$ | Relative biomass allocation coefficient for straw | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $R_p$ | Relative biomass allocation coefficient for product | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $R_r$ | Relative biomass allocation coefficient for roots | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop | $R_e$ | Relative biomass allocation coefficient for extra-root material | Holos default/External information（user defined） |CropParameterManager -> get_crop_parameter()|
| Crop group | $C_{concentration}$ | Carbon concentration of all plant parts ($kg \ kg^{-1}$) |Holos default/External information（user defined） |CropGroupManager -> get_crop_group()|
| Crop group | $S_p$ | Percentage of product yield returned to soil |Holos default/External information（user defined） |CropGroupManager -> get_crop_group()|
| Crop group | $S_s$ |Percentage of straw returned to soils|Holos default/External information（user defined） |CropGroupManager -> get_crop_group()|
| Crop group | $S_r$ | Percentage of roots returned to soil |Holos default/External information（user defined） |CropGroupManager -> get_crop_group()|
| Climate & soil | $P_i$ | Annual growing season precipitation (May – October), in ecodistrict “i” (mm) | Holos default/NASA POWER |ClimateSoilDataManager -> get_climate_soil_data|
| Climate & soil | $PE$ | Growing season potential evapotranspiration, by ecodistrict (May – October) | Holos default/NASA POWER |ClimateSoilDataManager -> get_climate_soil_data|
| Climate & soil | $FR\_Topo_{i}$ | Fraction of land occupied by lower portions of landscape | Holos default |ClimateSoilDataManager -> get_climate_soil_data|
| Modifiers / soil | $RF\_TX_{i}$ | Weighted modifier which provides a correction of the $EF_{Topo}$ in ecodistrict ‘‘i’’ based on the soil texture | Holos default/HWSD 2.0 |based on source == "default"[] ModifierSoilTexture -> get_rf_tx_modifier()/source == "external" [ExternalSoilTextureDataFetxher -> get_soil_texture()]|
| Modifiers | $RF\_CS$ | Reduction factor for Cropping System | Holos default/External information(user-defined) |Modifier -> get_modifier()|
| Modifiers | $RF\_NS$ | N source modifier RF_NS (SN = Synthetic Nitrogen; ON = Organic Nitrogen; CRN = Crop Residue Nitrogen) | Holos default/External information(user-defined) |Modifier -> get_modifier()|
| Modifiers | $RF\_AM$ | Reduction factor based on application method, only applicable to calculations of EF specific for SN | Holos default/External information(user-defined) |Modifier -> get_modifier()|
| Modifiers | $RF\_Till$ | Tillage modifier (Conservation or Conventional Tillage) | Holos default/External information(user-defined) |Modifier -> get_modifier()|

**RF_AM**

- controlled_release
- nitrification_inhibitor
- urease_inhibitor
- both_inhibitors
- default

**RF_CS**

- Annual
- Perennial

**RF_NS**

- RF_NS_CRN
- RF_NS_SN
- RF_NS_ON
- RF_NC_Unknown

**RF_Till**(eastern/western)

- reduced_tillage
- no_tillage
- intensive_tillage
- unknown