---
title: "Variables"
format: html
---
## GHG Emission Model Variables

### Crop 

| **Variable Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| $C_{p\_to\_soil}$ | Carbon input from product | kg C/ha | $Grain_N$ | Common | based on the crop type| 
| $C_r$ | Carbon input from root | kg C/ha | $Root_N$ | Common | based on the crop type| 
| $C_e$ | Carbon input from extra-root material | kg C/ha | $Exudate_N$ | Common | based on the crop type| 
| $C_s$ | Carbon input from straw | kg C/ha | $Straw_N$ | Common | based on the crop type| 
| $C_p$ | Plant carbon in agricultural product | kg C/ha | $C_r$,$C_s$,$C_e$,$C_{p\_to\_soil}$ | Common | based on the crop type|

### Climate

| **Variable Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| $EF_{{CT}_{P}}$ | Ecodistrict-level emission factor of precipitation | $(kgÂ N_2O-N)/Â (kgÂ N)$ | $EF$ | Common | based on the P and PE| 
| $EF_{{CT}_{PE}}$ | Ecodistrict-level emission factor of evapotranspiration | $(KgÂ N_2O-N)/Â (kgÂ N)$ | $EF$ | Common | based on the P and PE| 
| $EF_{TOPO}$ | $ğ‘_2ğ‘‚$ emission factor adjusted due to position in landscape and moisture regime | $kgÂ N_2O-N$ | $EF$ | Common | based on the P and PE| 

